[package]
name = "procon2022_comp_2nd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.12.1"
num = "0.4.0"
wav = "1.0.0"
wide = "0.7.5"
